services:
  - type: web
    name: kent-otel-backend-auto
    env: node
    rootDir: server
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: npm ci && npm run prisma:generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Postgres!2025-KentOtel@88.254.239.28:5432/kentotel
      - key: PRISMA_GENERATE
        value: enabled
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://xoser24.github.io/otelapp

staticSites:
  - name: otel-yonetim-frontend-auto
    rootDir: .
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    publishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: REACT_APP_SOCKET_URL
        value: https://kent-otel-backend-auto.onrender.com