databases:
  - name: kent-otel-db
    plan: free

services:
  - type: web
    name: kent-otel-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci && npm run prisma:generate && npx prisma db push --schema ../prisma/schema.prisma && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: kent-otel-db
      - key: CORS_ORIGIN
        fromSecret: CORS_ORIGIN

staticSites:
  - name: otel-yonetim-frontend
    rootDir: .
    plan: free
    buildCommand: npm ci && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_SOCKET_URL
        fromSecret: REACT_APP_SOCKET_URL